### ISSUE TITLE
Which retina face model are you using?

### ISSUE THREAD

**Issue by lakshaychhabra** [serengil/retinaface#10]
I can see there are various types of model available on arcface repo https://github.com/deepinsight/insightface/tree/master/model_zoo

Can you tell me which model are you using and why?

Also the it takes so much time to detect the face. If you are looking for optimising the inference time and need a hand, do let me know I would like to contribute.

**Comment by serengil** [comment]
this is a re-implementation from https://github.com/StanislasBertrand/RetinaFace-tf2

weights retrieved from the source: https://www.dropbox.com/s/g4f2lap9cyrdfw5/retinafaceweights.npy?dl=1
