### ISSUE TITLE
The retina face is too slow on a card with Arm64 Mali GPU.

### ISSUE THREAD

**Issue by TYeniyayla** [serengil/retinaface#101]
On the board whose features I have given below, it takes more than 2 minutes for the retina face to examine 1 single photo, and it takes a very long time for the camera to be activated. The only thing it does is to locate the face and the process of cropping and saving takes more than 2 minutes. Is there any way to speed this up? If there is a chance to speed it up using mali on this board with Arm 64 mali GPU, I would like to learn how.

Specifications
--
SOC | RockChip RK3566
CPU | Quad-core 64-bit Cortex-A55, 22nm lithography process, frequency up to 1.8GHz
GPU | ARM Mali-G52 2EESupports OpenGL ES 1.1/2.0/3.2. OpenCL 2.0. Vulkan 1.1Embedded high-performance 2D acceleration hardware
NPU | 1Tops@INT8, integrated high-performance AI accelerator RKNN NPUSupports one-click switching of Caffe/TensorFlow/TFLite/ONNX/PyTorch/Keras/Darknet
VPU | Supports 4K 60fps H.265/H.264/VP9 video decodingSupports 1080P 60fps H.265/H.264 video encodingSupports 8M ISP
RAM | 2GB / 4GB / 8GB LPDDR432Bit,supports all-data-link ECC
Storage | 32GB / 64GB / 128GB eMMCM.2 PCIe 2.0 × 1 (Expand with 2242 NVMe SSD)TF-Card Slot x1 (Expand with TF card)

**Comment by serengil** [comment]
No, unfortunately. You should not use retinaface model if time is your first concern and also not have strong hardware.
