### ISSUE TITLE
[BUG]: Confidence is wrong when examining rotated images

### ISSUE THREAD

**Issue by sathio** [serengil/retinaface#103]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/retinaface/issues) and [closed issues](https://github.com/serengil/retinaface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### RetinaFace's Version

0.0.17

### Python Version

3.12.3

### Operating System

mac os

### Dependencies

keras==3.3.3
retina-face==0.0.17
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.1
tf_keras==2.16.0

<img width="673" alt="image" src="https://github.com/serengil/retinaface/assets/1990816/60b37ee7-a4ee-44c6-97ad-e8ed59e8db5b">

<img width="700" alt="image" src="https://github.com/serengil/retinaface/assets/1990816/c846707e-d827-4b75-ac59-b9e37541350c">

![test2](https://github.com/serengil/retinaface/assets/1990816/fc9b2eab-0095-4a5d-a2a1-06fe38d91d73)

I'd need to find the correct orientation of the fake identity card I've posted, I'm trying to use the confidence index but for some reason it is higher when the image is rotated.

Ideally it should award the rotated image

### Reproducible example

```Python

def find_faces(image=None):

  images = {}
  rotate_angles = [0, 90, 180, 270]

  img = cv2.imread(image)
  img_base = img.copy()

  for angle in rotate_angles:

      logging.debug(f"Computing object detections... {image}@{angle}")
      img = img_base.copy()

      img = Image.fromarray(img)
      img = np.array(img.rotate(angle, expand=True))

      plt.imshow(img)
      plt.show()

      try:
          detections = RetinaFace.detect_faces(img)
      except Exception as exc:
          logging.critical(exc)
          continue

      if not isinstance(detections, dict):
          continue

      # loop over the detections
      for i, detection in detections.items():

          # logging.debug(detection)
          im = Image.open(image)
          im = im.rotate(angle, expand=True)
          confidence = detection.get('score', 0)

          # filter out weak detections by ensuring the `confidence` is greater than the minimum confidence
          if confidence > args.confidence:

              (startX, startY, endX, endY) = detection.get('facial_area')
              startX -= args.padding
              startY -= args.padding
              endX += args.padding
              endY += args.padding

              try:
                  text = confidence*100
                  logging.debug(f"Confidence of: {text} at {angle}")
                  im1 = im.crop((startX, startY, endX, endY))
                  im1 = im1.convert('RGB')

                  buffered = BytesIO()
                  im1.save(buffered, format="JPEG")

                  plt.imshow(im1)
                  plt.show()

                  img_str = base64.b64encode(buffered.getvalue()).decode()
                  images.update({text: [img_str, angle]})

              except Exception as exc:
                  logging.debug(exc)
                  pass

```

### Expected Result

confidence index should be higher when the image is rotated properly

### What happened instead?

the 90 degrees image wins

**Comment by serengil** [comment]
i would use nothing, retinaface is not for detecting face identities.
