### ISSUE TITLE
Adding Tinaface as backend: As Tinaface is lightweight model compared to Retinaface

### ISSUE THREAD

**Issue by Raghucharan16** [serengil/retinaface#104]
### Description

As Tinaface got better accuracy on wider [hard] dataset, and also light in weight when compared to retinaface, can you add this backend in your deepface or retinaface library? 
Or Can you implement a script using tinaface?

thanks

**Comment by serengil** [comment]
but this is retinaface project! please raise an enhancement request to deepface repo instead of retinaface.
