### ISSUE TITLE
[FEATURE]: Return face detection results along with alignment results

### ISSUE THREAD

**Issue by neeraj-kumar** [serengil/retinaface#108]
### Description

Right now, if a user wants both the face detection results (face box + location of fiducials) and alignment results, they have to call `detect_faces()` and `extract_faces()`, but the latter calls the former, so we are doing the work twice. Can there be either a different function, or a modified version of `extract_faces()` that returns the face detection results as well as extracted aligned faces?

**Comment by serengil** [comment]
If you call detect face, then you can extract facial area by yourself. TBH, a combined function is not necessary.
