### ISSUE TITLE
[FEATURE]: Eyes covering

### ISSUE THREAD

**Issue by patrickdalla** [serengil/retinaface#109]
### Description

Hi. I never used this software, but I will test it. I am a forensic expert, and work with some CSAM cases. I would like a feature to cover the eyes with some black box to better try to preserve the victim identity. It seems this tool extract the info necessary to make it possible. 
PS.: Maybe it is not the scope of this tool, so you can close it. You decide. Thanks in advance.

**Comment by serengil** [comment]
It is out of scope, but you can do it with retinaface.
