### ISSUE TITLE
[FEATURE]: Remove open-cv dependency

### ISSUE THREAD

**Issue by CodingAudrey2** [serengil/retinaface#110]
### Description

Hello, RetinaFace uses open-cv for things that PIL can do. The extra dependency bloats this package unnecessarily.

I actually have already written and tested the code to do this. I'm trying to push my branch so I can create a PR, but I'm getting this error:
`git -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/remove-open-cv-dependency:refs/heads/remove-open-cv-dependency --set-upstream`
`remote: Permission to serengil/retinaface.git denied to CodingAudrey2.`
`fatal: unable to access 'https://github.com/serengil/retinaface.git/': The requested URL returned error: 403`
I tried generating a new token and re-authenticating, but I'm getting the same error. 
This is my first time contributing to an open source project; is there anything I'm missing?

**Comment by serengil** [comment]
Thank you for your interest in contributing to RetinaFace! The issue you’re encountering with GitHub permissions is unrelated to the RetinaFace repository itself, so unfortunately, I can’t help resolve that specific GitHub issue.

Regarding your suggestion, I currently prefer using OpenCV for its robustness and versatility in handling image processing tasks in RetinaFace. At this time, I’m not looking to change that dependency.

**Comment by CodingAudrey2** [comment]
@serengil Would you be open to switching to the headless version of OpenCV?

**Comment by serengil** [comment]
I am very satisfied with opencv as is

**Comment by avarayr** [comment]
@serengil 
<img width="655" alt="image" src="https://github.com/user-attachments/assets/8732c87f-3421-4abf-9d1e-748b17e38083">

This is what you need opencv for?
