### ISSUE TITLE
[BUG]: h5py/h5t ValueError.  # I've installed the RetinaFace by git clone and pip install -e .

### ISSUE THREAD

**Issue by YYYYYangjijjia** [serengil/retinaface#115]
### Before You Report a Bug, Please Confirm You Have Done The Following...

- [X] I have updated to the latest version of the packages.
- [X] I have searched for both [existing issues](https://github.com/serengil/retinaface/issues) and [closed issues](https://github.com/serengil/retinaface/issues?q=is%3Aissue+is%3Aclosed) and found none that matched my issue.

### RetinaFace's Version

v0.0.17

### Python Version

3.9.20

### Operating System

Ubuntu 20.04.6 LTS

### Dependencies

absl-py==2.1.0
accelerate==0.16.0
addict==2.4.0
aiohappyeyeballs==2.4.3
aiohttp==3.10.10
aiosignal==1.3.1
annotated-types==0.7.0
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
astunparse==1.6.3
async-timeout==4.0.3
attrs==24.2.0
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
beautifulsoup4==4.12.3
bitsandbytes==0.45.0
blinker==1.9.0
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1
cfgv==3.4.0
charset-normalizer==3.4.0
clang==5.0
click==8.1.7
cmake==3.30.5
colorama==0.4.6
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1710320294760/work
contourpy==1.3.0
cycler==0.12.1
datasets==2.10.1
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1728594112391/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
-e git+https://github.com/serengil/deepface.git@ca6afd98efb87dc61fb022ddd2892da23dc75f68#egg=deepface
diffusers==0.13.1
dill==0.3.6
distlib==0.3.9
dlib==19.24.6
docker-pycreds==0.4.0
einops==0.8.0
eval_type_backport==0.2.0
exceptiongroup==1.2.2
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1725214404607/work
facexlib==0.3.0
filelock==3.16.1
filterpy==1.4.5
fire==0.7.0
Flask==3.1.0
Flask-Cors==5.0.0
flatbuffers==24.12.23
fonttools==4.54.1
frozenlist==1.5.0
fsspec==2024.10.0
ftfy==6.3.1
future==1.0.0
gast==0.4.0
gdown==5.2.0
gitdb==4.0.11
GitPython==3.1.43
google-auth==2.37.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
graphviz==0.20.3
grpcio==1.68.1
gunicorn==23.0.0
h5py==3.12.1
huggingface-hub==0.25.2
icecream==2.1.3
identify==2.6.3
idna==3.10
imageio==2.36.0
importlib_metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1726082825846/work
importlib_resources==6.4.5
iniconfig==2.0.0
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1719845459717/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1680185408135/work
ipywidgets==8.1.5
itsdangerous==2.2.0
jax==0.4.30
jaxlib==0.4.30
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
Jinja2==3.1.4
joblib==1.4.2
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1726610684920/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1727163409502/work
jupyterlab_widgets==3.0.13
**keras==3.7.0
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2**
kiwisolver==1.4.7
lazy_loader==0.4
libclang==18.1.1
lightgbm==4.5.0
lightning-utilities==0.11.9
lit==18.1.8
llvmlite==0.43.0
lmdb==1.5.1
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib==3.9.2
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1713250518406/work
mdurl==0.1.2
mediapipe==0.10.20
ml-dtypes==0.4.1
mpmath==1.3.0
mtcnn==0.1.1
multidict==6.1.0
multiprocess==0.70.14
mypy-extensions==1.0.0
namex==0.0.8
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1705850609492/work
networkx==3.2.1
nodeenv==1.9.1
numba==0.60.0
numpy==1.26.4
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
oauthlib==3.2.2
openai-clip==1.0.1
opencv-contrib-python==4.10.0.84
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
opt-einsum==3.3.0
optree==0.13.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1718189413536/work
pandas==2.2.3
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1712320355065/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1706113125309/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
pillow==11.0.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1726613481435/work
pluggy==1.5.0
pre_commit==4.0.1
prompt_toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1727341649933/work
propcache==0.2.0
protobuf==4.25.5
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1729847094652/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure_eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1721585709575/work
pyarrow==18.0.0
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
pydantic==2.10.4
pydantic_core==2.27.2
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1714846767233/work
pyiqa==0.1.13
pyparsing==3.2.0
pyre-extensions==0.0.23
PySocks==1.7.1
pytest==8.3.4
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
pytz==2024.2
PyYAML==6.0.2
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1728642231864/work
regex==2024.9.11
requests==2.32.3
requests-oauthlib==2.0.0
responses==0.18.0
-e git+https://github.com/serengil/retinaface.git@615a0cacfcb7ac10c6044d4d21b4fbcdb1e84cbe#egg=retina_face
rich==13.9.4
rsa==4.9
safetensors==0.4.5
scikit-image==0.24.0
scikit-learn==1.5.2
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy-split_1706041477036/work/dist/scipy-1.12.0-cp39-cp39-linux_x86_64.whl#sha256=1be674eb50c790f00bbecf6f8845364b19c49a5330a66198e2195eeeebd556e3
sentencepiece==0.2.0
sentry-sdk==2.19.2
setproctitle==1.3.4
six==1.15.0
smmap==5.0.1
sounddevice==0.5.1
soupsieve==2.6
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
sympy==1.13.1
tensorboard==2.18.0
tensorboard-data-server==0.7.2
tensorboard-plugin-wit==1.8.1
**tensorflow==2.18.0**
tensorflow-estimator==2.15.0
tensorflow-io-gcs-filesystem==0.37.1  
termcolor==1.1.0
**tf_keras==2.18.0**
threadpoolctl==3.5.0
tifffile==2024.8.30
timm==1.0.12
tokenizers==0.15.2
tomli==2.2.1
torch==1.13.1+cu116
torchvision==0.14.1+cu116
torchviz==0.0.2
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1724955920300/work
tqdm==4.66.6
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1713535121073/work
transformers==4.37.2
triton==2.0.0
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.2
urllib3==2.2.3
virtualenv==20.28.0
wandb==0.19.1
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1704731205417/work
Werkzeug==3.1.3
widgetsnbextension==4.0.13
wrapt==1.12.1
xformers==0.0.16
xxhash==3.5.0
yapf==0.43.0
yarl==1.17.0
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1726248574750/work 

### Reproducible example

```Python
pth = id_path_lst[0]
from retinaface import RetinaFace

resp = RetinaFace.detect_faces(pth)
```

### Relevant Log Output

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 16
     13 pth = id_path_lst[0]
     14 from retinaface import RetinaFace
---> 16 resp = RetinaFace.detect_faces(pth)
     18 # from deepface import DeepFace
     19 # obj = DeepFace.verify(pth,pth
     20 #           , model_name = 'ArcFace', detector_backend = 'retinaface')
     21 # print(obj["verified"])

File ~/retinaface/retinaface/RetinaFace.py:97, in detect_faces(img_path, threshold, model, allow_upscaling)
     94 # ---------------------------
     96 if model is None:
---> 97     model = build_model()
     99 # ---------------------------
    101 nms_threshold = 0.4

File ~/retinaface/retinaface/RetinaFace.py:54, in build_model()
     50 global model  # singleton design pattern
     52 if not "model" in globals():
     53     model = tf.function(
---> 54         retinaface_model.build_model(),
     55         input_signature=(tf.TensorSpec(shape=[None, None, None, 3], dtype=np.float32),),
     56     )
     58 # pylint: disable=possibly-used-before-assignment
     59 return model

File ~/retinaface/retinaface/model/retinaface_model.py:1514, in build_model()
   1496 face_rpn_cls_prob_reshape_stride8 = tf.transpose(
   1497     final, (1, 2, 3, 0), name="face_rpn_cls_prob_reshape_stride8"
   1498 )
   1500 model = Model(
   1501     inputs=data,
   1502     outputs=[
   (...)
   1512     ],
   1513 )
-> 1514 model = load_weights(model)
   1516 return model

File ~/retinaface/retinaface/model/retinaface_model.py:90, in load_weights(model)
     80 if os.path.isfile(exact_file) is not True:
     81     raise ValueError(
     82         "Pre-trained weight could not be loaded!"
     83         + " You might try to download the pre-trained weights from the url "
   (...)
     87         "manually.",
     88     )
---> 90 model.load_weights(exact_file)
     92 return model

File ~/miniforge3/envs/antidb-test/lib/python3.9/site-packages/tf_keras/src/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File ~/miniforge3/envs/antidb-test/lib/python3.9/site-packages/h5py/_hl/attrs.py:67, in AttributeManager.__getitem__(self, name)
     63 dtype = attr.dtype
     65 # Do this first, as we'll be fiddling with the dtype for top-level
     66 # array types
---> 67 htype = h5t.py_create(dtype)
     69 # NumPy doesn't support top-level array types, so we have to "fake"
     70 # the correct type and shape for the array.  For example, consider
     71 # attr.shape == (5,) and attr.dtype == '(3,)f'. Then:
     72 if dtype.subdtype is not None:

File h5py/h5t.pyx:1669, in h5py.h5t.py_create()

File h5py/h5t.pyx:1693, in h5py.h5t.py_create()

File h5py/h5t.pyx:1731, in h5py.h5t.py_create()

File h5py/h5t.pyx:1544, in h5py.h5t._c_string()

ValueError: Size must be positive (size must be positive)

**Comment by serengil** [comment]
your h5py package is not installed correctly, not a bug of retinaface
