### ISSUE TITLE
Wrong alignment direction issue when "align" set to True with DeepFace detectface using Retinaface detector

### ISSUE THREAD

**Issue by yvs997** [serengil/retinaface#12]
Dear Serengil,
We're encounter an issue according to align parameters in DeepFace ```detectface``` function, and we're using RetinaFace to achive the accuracy.

Here how we call the ```detectface``` function from DeepFace:
```
def face_detect(image):
    face = DeepFace.detectFace(img_path=image, detector_backend='retinaface', align=True)
    return face
```
and call it by this codes:
```
def detection(path):
    print (deepface.DeepFace)
    image = Image.open(path)
    image.show()
    face = DeepFace.detectFace(img_path=np.array(image),detector_backend='retinaface',align=True)
    imface = Image.fromarray((face * 255).astype(np.uint8))
    imface.show()
```
we do small experiment with rotated potrait (90 degree both clockwise and counter clockwise). We expect when align set to true, the face will be aligned. When we test both clockwise and counter clockwise, the output just rotating to other side (180 degree).
here is the sample image we get from Google search randomly and we rotate it in PS:
1st:
![counter90](https://user-images.githubusercontent.com/73321920/139612237-9fd218ac-281d-4923-a206-5856c2631a27.jpg)
2nd
![clockwise90](https://user-images.githubusercontent.com/73321920/139612242-a90d68c9-b41e-4f46-9da8-c6db6aac4485.jpg)

**Comment by serengil** [comment]
it seems that the model accuracy is poor for 90 degree rotated images. nothing to do to improve the accuracy because this is a re-implementation.

**Comment by yvs997** [comment]
so for this case, is there any future development to fix this thing?
