### ISSUE TITLE
Detection issues

### ISSUE THREAD

**Issue by d-01** [serengil/retinaface#13]
Hi! I have stumbled upon some strange cases where RetinaFace performs poorly on grayscale images for no apparent reason.

*RetinaFace (red), MTCNN (green)*

![retinaface-mtcnn_face-detection](https://user-images.githubusercontent.com/45796739/140274527-c2401c45-fac0-4359-a212-9296000d025c.png)

If you're interested in exploring behavior yourself, check out this Colab notebook: https://colab.research.google.com/drive/1jSkJLcgqZzqfgYdZKoFXItaxyBZEh3K_?usp=sharing

**Comment by serengil** [comment]
As mentioned in the read me of the repo, this is a re-implementation. You might consider to open an issue in the original repo.
