### ISSUE TITLE
(Not issue) need some help

### ISSUE THREAD

**Issue by netrunner-exe** [serengil/retinaface#23]
Hi! I need some help about face extraction. Currently i use installed from pip retinaface and use command provided in manual with some my modification:

```
resp = RetinaFace.detect_faces(frame)
faces = RetinaFace.extract_faces(img_path = frame, align = True)

i=1
for face in faces:
  filename = dir + 'face_'+str(i)+'.png'
  cv2.imwrite(filename, face)
  im_cv = cv2.imread(filename)
  im_rgb = cv2.cvtColor(im_cv, cv2.COLOR_BGR2RGB)
  cv2.imwrite(filename, im_rgb)
  i+=1
```
Question - can i extract and crop faces without some face parts, like without mouth? Something like that.
I'm new in python, if someone can help me or provide code example it will be really great! Thanks!
 
![IMG_20220110_122516](https://user-images.githubusercontent.com/81887288/148750823-9e8903e7-d0a2-44b5-88d1-39aebb7d394e.jpg)

**Comment by serengil** [comment]
you cannot do it with retinaface. 

I recommend you to study mediapipe: https://sefiks.com/2022/01/14/deep-face-detection-with-mediapipe/
