### ISSUE TITLE
pip install retina-face

### ISSUE THREAD

**Issue by mikila85** [serengil/retinaface#26]
$ pip install retina-face
Requirement already satisfied: retina-face in c:\users\michaell\appdata\local\programs\python\python310\lib\site-packages\retina_face-0.0.9-py3.10.egg (0.0.9)
Collecting Pillow>=5.2.0
  Using cached Pillow-9.0.0-cp310-cp310-win_amd64.whl (3.2 MB)
Collecting gdown>=3.10.1
  Using cached gdown-4.2.0.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.14.0
  Using cached numpy-1.22.1-cp310-cp310-win_amd64.whl (14.7 MB)
Collecting opencv-python>=3.4.4
  Using cached opencv_python-4.5.5.62-cp36-abi3-win_amd64.whl (35.4 MB)
Collecting retina-face
  Downloading retina_face-0.0.8-py3-none-any.whl (15 kB)
  Downloading retina_face-0.0.7-py3-none-any.whl (15 kB)
  Downloading retina_face-0.0.6-py3-none-any.whl (15 kB)
  Downloading retina_face-0.0.5-py3-none-any.whl (14 kB)
  Downloading retina_face-0.0.4-py3-none-any.whl (14 kB)
  Downloading retina_face-0.0.3-py3-none-any.whl (4.3 kB)
  Downloading retina_face-0.0.2-py3-none-any.whl (4.1 kB)
  Downloading retina_face-0.0.1-py3-none-any.whl (3.9 kB)
ERROR: Cannot install retina-face==0.0.1, retina-face==0.0.2, retina-face==0.0.3, retina-face==0.0.4, retina-face==0.0.5, retina-face==0.0.6, retina-face==0.0.7, retina-face==0.0.8 and retina-face==0.0.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    retina-face 0.0.9 depends on tensorflow>=1.9.0
    retina-face 0.0.8 depends on tensorflow>=1.9.0
    retina-face 0.0.7 depends on tensorflow>=1.9.0
    retina-face 0.0.6 depends on tensorflow>=1.9.0
    retina-face 0.0.5 depends on tensorflow>=1.9.0
    retina-face 0.0.4 depends on tensorflow>=1.9.0
    retina-face 0.0.3 depends on tensorflow>=1.9.0
    retina-face 0.0.2 depends on tensorflow>=1.9.0
    retina-face 0.0.1 depends on tensorflow>=1.9.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by serengil** [comment]
error message is clear. your tf version is imcompatible.

**Comment by john09282922** [comment]
> error message is clear. your tf version is imcompatible.

Hi, there is another error as well. could you upgrade it according to tf.version?
