### ISSUE TITLE
RetinaFace.detect_faces slow

### ISSUE THREAD

**Issue by waledmet** [serengil/retinaface#27]

**Comment by waledmet** [comment]
connection_string=0
video = cv2.VideoCapture(connection_string)
while video.isOpened():
grabbed, frame = video.read()
    if grabbed:
           print("before ==",datetime.datetime.now())
           resp = RetinaFace.detect_faces(frame, threshold = 0.1)
           print("after ==",datetime.datetime.now())


Time for detect_faces take around 5 second 
how can reduce this time

**Comment by serengil** [comment]
you cannot. retinaface is a complex model. 

but if you call it in a for loop, then second and the following ones will be responded sooner. because it spends a lot of time to build model and if you call it in a loop it will not build the model one more time.
