### ISSUE TITLE
Slow detection

### ISSUE THREAD

**Issue by ninnnnnnr** [serengil/retinaface#28]
Hello, very good recognition results! But very slow. My code:
`from retinaface import RetinaFace
import cv2
from datetime import datetime

start_time = datetime.now()

img_path = '/home/uba/Desktop/azs/video/test-opencv/frame0-03-56.52.jpg'
faces = RetinaFace.detect_faces(img_path)
print(faces)
print(datetime.now() - start_time)
img = cv2.imread(img_path)

for face in faces.keys():
  identity = faces[face]
  facial_area = identity['facial_area']
  cv2.rectangle(img, (facial_area[2], facial_area[3]), (facial_area[0], facial_area[1]), (255, 255, 255), 1)

cv2.imshow('', img)
cv2.waitKey(0)
cv2.destroyAllWindows()`

Computer:
AMD Ryzen 5 3600 6-Core Processor
GeForce GTX 1660
ram 16+16+8
Ubuntu 20.04

Why so slow ?

**Comment by ninnnnnnr** [comment]
result time my code 3 second

**Comment by serengil** [comment]
yes retinaface is very complex model and it runs slow

you might consider to use opencv if you have a speed concern.

**Comment by ninnnnnnr** [comment]
> yes retinaface is very complex model and it runs slow
> 
> you might consider to use opencv if you have a speed concern.

Is it possible to use GPU ?

**Comment by joaocassianox7x** [comment]
Yes @ninnnnnnr it's possible. Just check if your TensorFlow it's detecting the GPU with 

tf.test.gpu_device_name()
