### ISSUE TITLE
How to ensure that model weights are only downloaded once

### ISSUE THREAD

**Issue by sparshgarg23** [serengil/retinaface#31]
I was using your library to detect all the faces in my dataset.
When iterating through the folder,I recieved the following stack trace
```
File "/usr/local/lib/python3.7/dist-packages/retinaface/RetinaFace.py", line 68, in detect_faces
    model = build_model()
  File "/usr/local/lib/python3.7/dist-packages/retinaface/RetinaFace.py", line 34, in build_model
    retinaface_model.build_model(),
  File "/usr/local/lib/python3.7/dist-packages/retinaface/model/retinaface_model.py", line 678, in build_model
    model = load_weights(model)
  File "/usr/local/lib/python3.7/dist-packages/retinaface/model/retinaface_model.py", line 31, in load_weights
    os.mkdir(home+"/.deepface/weights")
FileExistsError: [Errno 17] File exists: '/root/.deepface/weight
```
I am assuming that  when you call
```
resp = RetinaFace.detect_faces("img1.jpg") 
```
it causes the weights to be downloaded,however when the next image comes it will again try to create the directories and try downloading the file.Since it already exists,the error is thrown.

Also,Rather than calling load_model multiple times,is it possible to just call it once.

Since the weights were only downloaded once,is there a way to ensure these are not downloaded again for the next batch of images?
Thanks

**Comment by serengil** [comment]
1- weights are downloaded once already. it seems that the following block says no folder for weights but os throws an exception when it tries to create one. could you check that is there a file named weight instead of folder in root/.deepface

```python
    if not os.path.exists(home+"/.deepface"):
        os.mkdir(home+"/.deepface")
        print("Directory ",home,"/.deepface created")

    if not os.path.exists(home+"/.deepface/weights"):
        os.mkdir(home+"/.deepface/weights")
        print("Directory ",home,"/.deepface/weights created")
```

2- load model uses the pre-created model in the memory. it will not build it from scratch.
```python
def build_model():
    
    global model #singleton design pattern
    
    if not "model" in globals():
        
        model = tf.function(
            retinaface_model.build_model(),
            input_signature=(tf.TensorSpec(shape=[None, None, None, 3], dtype=np.float32),)
        )

    return model
```
