### ISSUE TITLE
Get larger cropped, aligned faces

### ISSUE THREAD

**Issue by skjerns** [serengil/retinaface#37]
Currently the extracted faces are cropped to a very narrow region around the landmarks, often times cropping out the chin or the hair.

Is is possible to set the bounding box of cropping after alignment/rotation to get larger crops?

Specifically, I would like to have the faces, but with a bit of the surrounding for a timelapse.

**Comment by serengil** [comment]
sure, we can add 10% area outside optionally

i will add this feature in the next release. meanwhile, this issue will be in open status.

**Comment by skjerns** [comment]
I think being able to set the size of the cropping area (centered around the face) would be great, not using a static value.

Thanks!

**Comment by bharateshwq** [comment]
is this implemented yet??
