### ISSUE TITLE
Use Case and High-Level Description

### ISSUE THREAD

**Issue by NguyenTrongThinh** [serengil/retinaface#39]
Is there any document that describe the output of model that human can read? Or please help me a method to understand the output. I found one document on the internet, but I am not sure whether it is correct or not for model in this repo: https://docs.openvino.ai/2021.2/omz_models_public_retinaface_resnet50_retinaface_resnet50.html

My target is run this model in mobile devices. I can covert and get the **net_out**. I would like to parse **net_out** to get the **score, facial_area, landmarks**.  I am not familiar with Python so I don't understand clearly what it does to parse **net_out** in detect_faces function.

**Comment by serengil** [comment]
i am not the designer of retinaface model. you might research this from its original research paper. this is just an implementation and it is working. that is all the responsibility of the package.
