### ISSUE TITLE
Disable Keras progression bar

### ISSUE THREAD

**Issue by amar-enkhbat** [serengil/retinaface#42]
It's a bit annoying that retinaface keeps showing Keras progression bar on every detection. It's especially taxing to Jupyter notebook where it starts to lag after a few hundred faces. I think there should be an option like in deepface where we can set prog_bar=True/False.

**Comment by serengil** [comment]
which function you are using and how?

**Comment by serengil** [comment]
if you downgrade tensorflow, this is going to be sorted. i am using 2.7.4.
