### ISSUE TITLE
Image resolution for inference

### ISSUE THREAD

**Issue by Micky-123** [serengil/retinaface#50]
Hi,
What is the default image resolution on which the model operates? I tried with 360p and 1080p and it took the same time, so I guess the middleware code is rescaling all the images to a particular resolution before doing inference. Can you please let me know. 
Also, is the default model based on resnet-50 or resnet-152? 
I would like to experiment with different models. Is it possible to download models based on different resnet backbone and mobilenet backbone? 
Thanks!

**Comment by serengil** [comment]
1- it does not have a pre-defined shape

```python
# https://github.com/serengil/retinaface/blob/master/retinaface/model/retinaface_model.py#L55
data = Input(dtype=tf.float32, shape=(None, None, 3), name='data')
```

2- backbone is resnet-50 as mentioned [here](https://github.com/StanislasBertrand/RetinaFace-tf2) and [here](https://github.com/StanislasBertrand/RetinaFace-tf2/issues/3). no you cannot switch models.
