### ISSUE TITLE
Question regarding verify function

### ISSUE THREAD

**Issue by Micky-123** [serengil/retinaface#51]
Hi,

I use RetinaFace for face detections. So,, I have the face coordinates in a particular frame. Now, I want to use Verify() function to see if it matches the other stored face. I have the face coordinates from both the frames - meaning to say that I don't want the verify function to detect the face again but I only want the function to verify if both the faces are matching or not. How can I achieve it? I am trying to do this to increase the speed of the verify function call. Can you please suggest.

Thanks!

**Comment by serengil** [comment]
does not deepface stream function do this?
