### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'

### ISSUE THREAD

**Issue by sathio** [serengil/retinaface#53]
Hi, I'm receiving this error when trying your code, I've found that it's due to the latest np versions after they've removed the 

`np.int` and  `np.float` attributes 

https://levelup.gitconnected.com/fix-attributeerror-module-numpy-has-no-attribute-float-d7d68c5a4971

if I manually replace `np.float` and `np.int` occurrences it works fine

**Comment by serengil** [comment]
thank you for information. currently repo has a pr covering this issue. will be resolved soon.

**Comment by serengil** [comment]
release published
