### ISSUE TITLE
detect_faces(image) return ndarray

### ISSUE THREAD

**Issue by ZxUkr** [serengil/retinaface#54]
detect_faces(image) return ndarray instead of dict like that 
`{
    "face_1": {
        "score": 0.9993440508842468,
        "facial_area": [155, 81, 434, 443],
        "landmarks": {
          "right_eye": [257.82974, 209.64787],
          "left_eye": [374.93427, 251.78687],
          "nose": [303.4773, 299.91144],
          "mouth_right": [228.37329, 338.73193],
          "mouth_left": [320.21982, 374.58798]
        }
  }
}`

That is happend at https://github.com/serengil/retinaface/blob/b6343aa59e7a127862ba8bbd21d06dcee260e562/retinaface/RetinaFace.py#L146

What is mean?

**Comment by serengil** [comment]
no face found in that case.
