### ISSUE TITLE
Add URL Input like Deepface

### ISSUE THREAD

**Issue by ColludingPudding** [serengil/retinaface#57]
First of all, this is such a great repo, the examples are well written and easy to read. I just have a small caveat for input.

I am working on a snippet using both retinaface and deepface, and I'm having some consistency issues with the input. I was wondering if we could add URL input to retinaface the same way it's implemented in deepface? I copied the snippet in deepface and changed load_image to get_image to stay consistent with retinaface. If this doesn't work, I'd love for url input to be added to retinaface soon. 

```
import base64
import PIL.Image
import requests

def loadBase64Img(uri):
    encoded_data = uri.split(",")[1]
    nparr = np.fromstring(base64.b64decode(encoded_data), np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    return img

def get_image(img):
    exact_image = False
    base64_img = False
    url_img = False

    if type(img).__module__ == np.__name__:
        exact_image = True

    elif img.startswith("data:image/"):
        base64_img = True

    elif img.startswith("http"):
        url_img = True

    # ---------------------------

    if base64_img is True:
        img = loadBase64Img(img)

    elif url_img is True:
        img = np.array(PIL.Image.open(requests.get(img, stream=True, timeout=60).raw).convert("RGB"))

    elif exact_image is not True:  # image path passed as input
        if os.path.isfile(img) is not True:
            raise ValueError(f"Confirm that {img} exists")

        img = cv2.imread(img)

    return img
```

**Comment by serengil** [comment]
yes, i am planning use same approach. you do not have to do anything. just wait please.

**Comment by ColludingPudding** [comment]
Thank you so much! Looking forward to it!

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/retinaface/pull/73
