### ISSUE TITLE
How do I enable CUDA support?

### ISSUE THREAD

**Issue by martinenkoEduard** [serengil/retinaface#58]

**Comment by serengil** [comment]
Install tensorflow-gpu dependency first

**Comment by martinenkoEduard** [comment]
> Install tensorflow-gpu dependency first

What version of tensorflow-gpu should I use?

**Comment by martinenkoEduard** [comment]
It worked - but it only uses 1% of 3080 gpu.
Is there a way to improve perfomance?

**Comment by serengil** [comment]
it seems that it is enough. tf handles gpu related things. we are not customizing anything in the library side.
