### ISSUE TITLE
rotated faces

### ISSUE THREAD

**Issue by fisakhan** [serengil/retinaface#6]
In my experience, retinaface cannot precisely locate the 5 landmarks on rotated faces, especially for 90 degrees and more rotation. How to solve that problem without rotating the input image? Or can we find that the face is rotated thats why the landmarks are not good?
![Obama](https://user-images.githubusercontent.com/48552619/130209133-ec81b4df-37df-4f07-a48a-2f1298a412a1.jpg)
![obm](https://user-images.githubusercontent.com/48552619/130209735-db93d347-d4e4-4fcd-909d-dc86e97afeff.jpg)
![obmR](https://user-images.githubusercontent.com/48552619/130209739-78835daa-b749-4626-a398-62162f090848.jpg)

**Comment by serengil** [comment]
do you have some testing samples? please share them here.

**Comment by serengil** [comment]
this repo is a re-implementation and nothing to do to improve the accuracy in those conditions.

**Comment by saskra** [comment]
> this repo is a re-implementation and nothing to do to improve the accuracy in those conditions.

Too bad, where is the best place to send such a request? I would also like to be able to recognize upside down and sideways faces.
