### ISSUE TITLE
Using GPU; tensorflow-gpu deprecated

### ISSUE THREAD

**Issue by edavalosanaya** [serengil/retinaface#61]
Hello,

The `tensorflow-gpu` dependency is out-dated and cannot be installed as easily, thereby making the use of a GPU difficult. Sorry for the trouble, but is there a way this can be more streamlined and up-to-date (one of the major advantages of the `retinaface` package is its ease of use and installation)?

**Comment by serengil** [comment]
newer tf versions should support gpu by default.

**Comment by FurkanGozukara** [comment]
> newer tf versions should support gpu by default.

what do we need to install to use gpu

not using my gpu

here my code

def detect_and_move_image(org_image_path, target_folder_single, target_folder_multiple):
    faces = RetinaFace.detect_faces(org_image_path)
    num_faces = len(faces)
    # pip install retina-face

    print("There are ", len(faces), " faces in the image")

    if num_faces == 1:
        move_image(org_image_path, target_folder_single)
    if num_faces > 1:
        move_image(org_image_path, target_folder_multiple)
    if num_faces < 0:
        move_image(org_image_path, target_folder_0)
