### ISSUE TITLE
Working for some images, not working for some even in case of a clear picture

### ISSUE THREAD

**Issue by jokerisgod** [serengil/retinaface#62]
Hi,

I tried retinaface on below picture. 
[https://c.gawby.com/file/mjaymg/mdg/mdm/mdu/ntc/u/j/o/ujjwal-chopra-612566686.jpg](https://c.gawby.com/file/mjaymg/mdg/mdm/mdu/ntc/u/j/o/ujjwal-chopra-612566686.jpg)

It doesn't work, and returns 
`(array([], shape=(0, 5), dtype=float64), array([], shape=(0, 5, 2), dtype=float64))`

**Comment by evolseven** [comment]
I have noticed this same thing with close cropped images, I haven't been able to nail it down.. but I added a helper function to pad the image and redo the detection.. seems like just putting the image in the top left corner and filling with black seems to make detections work.. I don't know why it does this.. but in the case of no detections I run the image through this function.. originally I was centering the image in the black background and that worked as well, but it had the side effect of the coordinates being incorrect, by putting it in the top left corner there is no adjustments needed for the coordinates.. an example pad function is (assuming a cv2 image):

def padImage(img):
    (w,h,c) = img.shape
    maxdim = np.max([w,h])
    paddeddim = int((maxdim/1024) + 1) * 1024
    img2 = np.zeros((paddeddim,paddeddim,3),dtype=np.float32)
    img2[0:w,0:h] = img
    return img2

It does seem odd as the images of this type seem almost ideal for face detection but yet it doesn't work.  Note that this worked for insightface, not retinaface directly but I believe it uses the same methods/models and so the solution and cause is likely similar.

**Comment by serengil** [comment]
Try to set threshold to a smaller value. I got successful result for the given image.

Not working

```python
RetinaFace.detect_faces("input.jpg")
```

Working

```python
RetinaFace.detect_faces("input.jpg", threshold = 0.1)
```
