### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by htcml** [serengil/retinaface#63]
Does the RetinaFace implementation of this repo have the same performance as the original insightface implementation? It seems this Retina implementation performs even worse than MTCNN.

**Comment by serengil** [comment]
1- this is re-implementation
2- this shares same structure with the original study. so, performance with respect to the speed must have similar score to original study.
3- mtcnn is faster than retinaface, but face detection score is higher in retinaface.

**Comment by htcml** [comment]
You'd better to do your own benchmark study to assert that "face detection score is higher in retinaface". Based on what I observed, its score should be below 50.

**Comment by serengil** [comment]
i did not train anything in this repo. this is using pre-trained weights of this study: https://github.com/StanislasBertrand/RetinaFace-tf2

Scores are already mentioned there.

Model | Easy | Medium | Hard
-- | -- | -- | --
Original Mxnet implementation | 96.5 | 95.6 | 90.4
Ours | 95.6 | 94.6 | 88.5
