### ISSUE TITLE
Doubt: Inside the Preprocessfunction , not changing the dimension to (N,C,H,W)  ? 

### ISSUE THREAD

**Issue by mathanprasannakumar** [serengil/retinaface#66]
Hey , seregil,
In the preprocess_image function ,you described changing the image dim from (N,H,W,C) to (N,C,H,W) , but  the below  code only reversing the channels only (FROM BGR to RGB)

`# Make image scaling + BGR2RGB conversion + transpose (N,H,W,C) to (N,C,H,W)

    for i in range(3):
        im_tensor[0, :, :, i] = (img[:, :, 2 - i] / pixel_scale - pixel_means[2 - i]) / pixel_stds[2 - i]`

Is it a mistake or written purposely ? 
Kindly correct me if i am wrong.

**Comment by serengil** [comment]
as mentioned in the read me, this is a re-implementation. i copied some code blocks from original repo.

**Comment by mathanprasannakumar** [comment]
Thanks for the clarification Serengil.
