### ISSUE TITLE
Face Alignment - 1st, Extraction - 2nd

### ISSUE THREAD

**Issue by victortrintea** [serengil/retinaface#67]
My challenge with RetinaFace is that I haven't found a way yet how to first detect the face, second, align the image based on the eyes line, and third, only after that to extract the image and export the face as an separate image file.

Only in this way it can be avoided the data lost (black areas, as a result of extraction first following by alignment).

Thanks you for your project. It's awesome and it's pretty straight forward.

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/retinaface/pull/75
