### ISSUE TITLE
ValueError while calling RetinaFace.detect_faces('img3.jpg') or RetinaFace.build_model()

### ISSUE THREAD

**Issue by AjinkyaG** [serengil/retinaface#68]
Getting this same error : ValueError: The channel dimension of the inputs should be defined. The input_shape received is (None, None, None, 9), where axis -3 (0-based) is the channel dimension, which found to be `None`.
TF version is 2.9.1 , Please let me know if I am missing anything.

**Comment by serengil** [comment]
Seems this was a channels order issue.

Try to change keras config to channels_last and run

**Comment by serengil** [comment]
Closed due to inactivity
