### ISSUE TITLE
High VRAM usage on Linux

### ISSUE THREAD

**Issue by brandostrong** [serengil/retinaface#69]
Running via docker with gpu access, in an environment with only retina-face, and I run out of vram. More curiously, my VRAM spikes to max whilst it's downloading for the first time, then OOMs when the download finishes. Any idea what's going on here? I am using a 4090, so I definitely have the vram.

My Docker base image is nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

**Comment by brandostrong** [comment]
Disabling gpu access results in much faster cpu usage, about 1 image per second, but obviously isn't optimal.

**Comment by zux-hidden** [comment]
docker ..... -e TF_FORCE_GPU_ALLOW_GROWTH=true fix it
