### ISSUE TITLE
from retinaface import RetinaFace

### ISSUE THREAD

**Issue by onlinehuazai** [serengil/retinaface#7]
ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1K3Eq2k1b9dpKkucZjPAiCCnNzfCMosK4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa088499f28>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by serengil** [comment]
Message is clear. You cannot access the target github address. Are you using proxy? Try to disable it.

You can download the pre-trained weight to ~/.deepface/weights folder manually.

Link: https://github.com/serengil/deepface_models/releases/download/v1.0/retinaface.h5

**Comment by Kanishk-kaushik16** [comment]
How to call Deepface build method manually . I have same error I downloaded the retinaface.h5 from github but when I don't find a way to call the file manually.
