### ISSUE TITLE
Which library versions do you suggest for maximum GPU performance on Windows?

### ISSUE THREAD

**Issue by FurkanGozukara** [serengil/retinaface#70]
Dear @serengil, I am using below. Working decent. Using almost 24 GB VRAM on RTX 3090 TI

Windows 10 Python 3.10.11

Do you suggest anything else?

Installing on a fresh venv

```
pip3 install torch==2.0.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

pip install tensorflow==2.10

pip install transformers

pip install Pillow

pip install retina-face
```

I also compared RTX 3090 TI and RTX 3060 on same PC

Both speed are same. GPU utilization is pretty low according to nvidia-smi

![image](https://github.com/serengil/retinaface/assets/19240467/898793b4-4655-4323-8d49-c9352ba6320b)

**Comment by serengil** [comment]
if you install tensorflow-gpu before installing retinaface, then it will use gpu by default.

**Comment by mk148a** [comment]
@serengil  which version is best for  retina-face use for tensorflow 2.10?
