### ISSUE TITLE
Retina-face forces the installation of full tensorflow, even when tensorflow-cpu is already installed

### ISSUE THREAD

**Issue by volanin** [serengil/retinaface#79]
Hello,

I have a project that uses AWS Lambdas to detect faces. AWS Lambdas don't have access to hardware GPU, and they have some strict limits about image size and execution time. To make my images smaller and startup as fast as possible, I opt to install tensorflow-cpu (which is about ~200MB).

But even with tensorflow-cpu already installed, when I install retina-face it also forces the installation of the full tensorflow with GPU support (which is about ~490MB). Since tensorflow-cpu works fine with retina-face, I think retina-face installation should check if tensorflow-cpu already installed and, in this case, skip the installation of the full tensorflow.

Here is my requirements.txt:

opencv-contrib-python==4.9.0.80
opencv-python==4.9.0.80
protobuf==3.20.3
tensorflow-cpu==2.14
retina-face==0.0.14

Thank you.

**Comment by serengil** [comment]
Try to install retinaface with no dependencies

pip install retina-face --no-deps

**Comment by volanin** [comment]
Retina-face has other necessary dependencies that must be installed and cannot be ignored. I could install all of them manually, but honestly, it's a pain and the installation might break later if retina-face adds more dependencies in future versions (I would need to manually add the new dependencies to requirements.txt). This kind of manual dependency management is exactly what pip intends to avoid.

Anyway, I understand the 'not planned' status.
Thanks for taking the time to check this issue.
