### ISSUE TITLE
face bounding box info in RetinaFace.extract_faces(fname, threshold=0.9, model = retina_model, align = True)

### ISSUE THREAD

**Issue by lightsailpro** [serengil/retinaface#8]
Is the bounding box info also available in the result of RetinaFace.extract_faces? Need bounding box to combine and visualize both face detection(RetinaFace.detect_faces) and face analysis (RetinaFace.extract_faces, DeepFace.analyze) result. But it seems that the face_id returned from RetinaFace.detect_faces can be different order from the one from RetinaFace.extract_faces. This will mess up the face_id linkage between the  visual of the detected face and the emotion/race analysis from RetinaFace.extract_faces and DeepFace.analyze. Thanks

**Comment by serengil** [comment]
extract_faces uses detect_faces directly. You can confirm it here: https://github.com/serengil/retinaface/blob/master/retinaface/RetinaFace.py
