### ISSUE TITLE
alignment_procedure crashes when both eyes are in the same position

### ISSUE THREAD

**Issue by Dobiasd** [serengil/retinaface#94]
When looking at a face from the side, the landmark detector may give the same position for both eyes.

In that case, `retinaface.commons.postprocess.alignment_procedure` crashes with `UnboundLocalError: cannot access local variable 'angle' where it is not associated with a value`.

Some IDEs also highlight this problem:

![IPjqZfD](https://i.imgur.com/IPjqZfD.png)

Here is a minimal example to reproduce the problem:

```python3
import numpy as np
from retinaface.commons import postprocess

postprocess.alignment_procedure(np.zeros([123, 123, 3], dtype=np.uint8), (10, 10), (10, 10), (33, 33))
```

**Comment by Dobiasd** [comment]
Of course, it would be nice if `pylint` would catch such problems already in the CI.

I've opened [a StackOverflow question](https://stackoverflow.com/questions/78191580/how-to-catch-potentially-undefined-variables-with-pylint) asking if enabling such a check is possible.

**Comment by serengil** [comment]
Good spot! Do you mind to share your input image? Would be easier to fix if i can reproduce.

**Comment by Dobiasd** [comment]
It happened while processing a video stream. I no longer have the problematic frame, but I'll try to reproduce one by moving in front of my webcam. :man_dancing:

**Comment by Dobiasd** [comment]
I've [tried](https://gist.github.com/Dobiasd/42d2119148e985d181d0127f7fa64e4d), but so far failed to align my head in a pose to fulfill the required condition.

Hope you can maybe fix it even without such an example image.

**Comment by serengil** [comment]
No problem, we can still fix it.

**Comment by serengil** [comment]
@Dobiasd if we set an initial 0 value to angle in alignment produce function, then this will be sorted.

Do you mind to create a PR for this? I would like to see your name as a contributor because you found this issue.

https://github.com/serengil/retinaface/blob/master/retinaface/commons/postprocess.py#L33

**Comment by Dobiasd** [comment]
FYI:

While `pylint` is not able to catch such bugs in the linter step, `mypy` (with `--enable-error-code possibly-undefined`) is. :tada:

So in case you're interested in preventing such issues automatically in the future, using `mypy` could be an option. :slightly_smiling_face:

**Comment by serengil** [comment]
Oh no, very satisfied with pylint, do not want to switch anything else :)

**Comment by Dobiasd** [comment]
Ah, no, I did not mean to replace `pylint` with `mypy`, but adding `mypy` to the CI. `mypy` is a type checker and solves different problems than `pylint` (a linter) does. Not only our team at work, but also me in my private projects ([example](https://github.com/Dobiasd/undictify)) use both in conjunction, and I like this combination a lot. :slightly_smiling_face:
