### ISSUE TITLE
detect_faces image preprocessing?

### ISSUE THREAD

**Issue by utility-aagrawal** [serengil/retinaface#96]
Hi,

I see that images are upscaled before running them through the model in detect_faces(). Why is that so? My understanding is that retinaface expects input image of 640 x 640 but that's not what images are upscaled to? Can you please explain the reasoning behind the upscaling?

Thanks!

**Comment by serengil** [comment]
Hi,

As I [added ](https://github.com/serengil/retinaface/blob/master/retinaface/commons/preprocess.py#L89)comments into the source code, that logic is copied from another repo. TBH, I do not know the reason behind it.

**Comment by utility-aagrawal** [comment]
No problem, Thanks for your response! Let me see if they can answer it.
