### ISSUE TITLE
When extracting faces, sometimes function will return empty array if face is not completely in view.

### ISSUE THREAD

**Issue by newbiemate** [serengil/retinaface#98]
I have a lot of photos that have groups of people in it. I was trying out this library to extract their face vector information, but it seems like when it encounters a face that's not fully in view (like cut off on the side), the face extraction function returns an empty array for that person.

Here is an example:

```
import matplotlib.pyplot as plt
from retinaface import RetinaFace

faces = RetinaFace.extract_faces(img_path = "test.jpg", align = True)
for face in faces:
  plt.imshow(face)
  plt.show()
```

The test image:
![test](https://github.com/serengil/retinaface/assets/34783617/d68da6c3-3d0c-41c7-a496-0b6e8d75d21f)

The above code will crash because on the very last person the function will return an empty array and matplotlib will fail due to trying to render something that has no data:

ie,
```
ValueError: zero-size array to reduction operation minimum which has no identity
```

`RetinaFace` will find everyone except the person on the very left, whose face is cut off. I'm new to face detection stuff, so I'm not sure if this is a bug or if deepface has a way to improve detection of these types of faces. Any help appreciated!

**Comment by serengil** [comment]
it worked for me

**Comment by serengil** [comment]
if you set the threshold to a lower value, then it will find faces easily.

https://github.com/serengil/retinaface/blob/master/retinaface/RetinaFace.py#L210

**Comment by newbiemate** [comment]
@serengil Could you share what values you used? I tried lowering it:

```
faces = RetinaFace.extract_faces(img_path = "test.jpg", align = True,  threshold=0.01)
```
But I'm still getting an empty array.

**Comment by serengil** [comment]
I used the default one. You can find the result in the attachment.

```python
from retinaface import RetinaFace
import matplotlib.pyplot as plt

img_path = "x.jpg"

faces = RetinaFace.extract_faces(img_path = img_path, align = True)

for face in faces:
  plt.imshow(face)
  plt.show()
```

which version are you using? this is mine

```shell
(base) sefik@L-GCCDXDDT:~/workspace/facial-recognition-benchmarks-main$ pip show retina-face
Name: retina-face
Version: 0.0.13
```

![Untitled](https://github.com/serengil/retinaface/assets/18491038/f5fc2fae-344b-4df1-af27-75240051b579)

**Comment by serengil** [comment]
Closed with PR - https://github.com/serengil/retinaface/pull/100
